// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Link struct {
	ID   string `json:"id"`
	URL  string `json:"url"`
	Hash string `json:"hash"`
}

type NewLink struct {
	URL string `json:"url"`
}
