// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Link struct {
	ID    string `json:"id"`
	URL   string `json:"url"`
	Short string `json:"short"`
}

type NewLink struct {
	URL string `json:"url"`
}
